//! Generates the alias script and registers ONE line in the shell rc
//! (requirements §5, §6).
//!
//! This is the most dangerous module in the app. A GUI editing a shell startup
//! file with string surgery is a foot-gun: corrupt it once and the terminal
//! will not open — and you need a terminal to fix it.
//!
//! Two rules keep the blast radius at zero:
//!
//! 1. The app owns `~/.agentport/profiles.sh` entirely and rewrites it freely.
//! 2. The shell rc receives exactly ONE line, exactly once, and it is checked
//!    for before being added. Skipping that check is what produced seven
//!    duplicate `# Added by Antigravity` lines in a real `.zshrc` (evidence #5).

use crate::model::{CliKind, Profile};
use std::fs;
use std::path::{Path, PathBuf};

/// Marker used to find our line in an rc file regardless of surrounding edits.
const RC_MARKER: &str = "agentport/profiles";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellKind {
    Posix,      // zsh, bash
    PowerShell, // Windows
}

/// Result of touching the rc file — the UI needs to distinguish these to tell
/// the user whether they must open a new terminal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RcOutcome {
    /// The line was added; the user needs a new shell.
    Added,
    /// The line was already present; nothing was written.
    AlreadyPresent,
}

pub fn app_dir(home: &Path) -> PathBuf {
    home.join(".agentport")
}

pub fn script_path(home: &Path, shell: ShellKind) -> PathBuf {
    match shell {
        ShellKind::Posix => app_dir(home).join("profiles.sh"),
        ShellKind::PowerShell => app_dir(home).join("profiles.ps1"),
    }
}

/// The single line an rc file receives. Never changes across versions —
/// changing it would orphan the old line in everyone's rc.
pub fn rc_line(home: &Path, shell: ShellKind) -> String {
    let p = script_path(home, shell);
    match shell {
        ShellKind::Posix => format!("[ -f {0} ] && . {0}", p.display()),
        ShellKind::PowerShell => {
            format!("if (Test-Path {0}) {{ . {0} }}", p.display())
        }
    }
}

/// True when this rc already sources our script, whatever the exact wording.
///
/// Matches on the marker rather than the full line so a hand-edited path, an
/// older line format, or different quoting still counts as present. Being
/// generous here is deliberate: a false negative appends a duplicate, which is
/// the failure this exists to prevent.
pub fn rc_already_registered(rc_text: &str) -> bool {
    rc_text
        .lines()
        .filter(|l| !l.trim_start().starts_with('#'))
        .any(|l| l.contains(RC_MARKER))
}

/// Adds the line to an rc file if — and only if — it is not already there.
pub fn ensure_rc_line(rc_path: &Path, home: &Path, shell: ShellKind) -> Result<RcOutcome, String> {
    let existing = fs::read_to_string(rc_path).unwrap_or_default();

    if rc_already_registered(&existing) {
        return Ok(RcOutcome::AlreadyPresent);
    }

    let mut out = existing;
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("\n# agentport\n");
    out.push_str(&rc_line(home, shell));
    out.push('\n');

    fs::write(rc_path, out).map_err(|e| format!("cannot write {}: {e}", rc_path.display()))?;
    Ok(RcOutcome::Added)
}

/// Renders the full alias script. The app owns this file outright.
pub fn render_script(home: &Path, profiles: &[Profile], shell: ShellKind) -> String {
    match shell {
        ShellKind::Posix => render_posix(home, profiles),
        ShellKind::PowerShell => render_powershell(home, profiles),
    }
}

fn header(comment: &str) -> String {
    format!(
        "{comment} GENERATED BY agentport — DO NOT EDIT\n\
         {comment} Edits here are lost the next time agentport writes profiles.\n\
         {comment} Uninstalling agentport means deleting this file and the one\n\
         {comment} line that sources it from your shell startup file.\n\n"
    )
}

fn render_posix(home: &Path, profiles: &[Profile]) -> String {
    let mut out = header("#");

    for p in profiles {
        let cfg = crate::writer::config_path(home, p).display().to_string();
        // The key is passed as a per-command environment variable rather than
        // exported. An exported key is visible to every child process on the
        // machine — the state a real `.zshrc` was found in.
        let body = match p.cli {
            CliKind::Claude => format!(
                "{env}={key} command claude --settings {cfg} \"$@\"",
                env = p.env_var,
                key = shell_quote(&p.api_key),
                cfg = shell_quote(&cfg),
            ),
            CliKind::Codex => format!(
                "{env}={key} command codex --profile {alias} \"$@\"",
                env = p.env_var,
                key = shell_quote(&p.api_key),
                alias = shell_quote(&p.alias),
            ),
        };

        // A function, not an alias: aliases cannot take arguments, and every
        // flag the CLI accepts must pass straight through.
        out.push_str(&format!(
            "# {alias} -> {provider}\n{fname}() {{\n  {body}\n}}\n\n",
            alias = p.alias,
            provider = p.provider,
            fname = p.alias,
            body = body,
        ));
    }

    out
}

fn render_powershell(home: &Path, profiles: &[Profile]) -> String {
    let mut out = header("#");

    for p in profiles {
        let cfg = crate::writer::config_path(home, p).display().to_string();
        // PowerShell aliases cannot take arguments at all, so a function is the
        // only option here — not merely the better one.
        let invoke = match p.cli {
            CliKind::Claude => format!(
                "  & claude --settings {cfg} @args",
                cfg = ps_quote(&cfg)
            ),
            CliKind::Codex => format!(
                "  & codex --profile {alias} @args",
                alias = ps_quote(&p.alias)
            ),
        };

        out.push_str(&format!(
            "# {alias} -> {provider}\nfunction {fname} {{\n  \
             $env:{env} = {key}\n{invoke}\n}}\n\n",
            alias = p.alias,
            provider = p.provider,
            fname = p.alias,
            env = p.env_var,
            key = ps_quote(&p.api_key),
            invoke = invoke,
        ));
    }

    out
}

/// Single-quotes a value for POSIX shells, escaping embedded quotes.
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// Single-quotes a value for PowerShell, where '' escapes a quote.
fn ps_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// Writes the script file, creating the app directory if needed.
pub fn write_script(
    home: &Path,
    profiles: &[Profile],
    shell: ShellKind,
) -> Result<PathBuf, String> {
    let dir = app_dir(home);
    fs::create_dir_all(&dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;

    let path = script_path(home, shell);
    fs::write(&path, render_script(home, profiles, shell))
        .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    Ok(path)
}

/// Alias names are TYPED at a terminal, unlike filenames which are only read.
pub fn validate_alias(alias: &str) -> Result<(), String> {
    if alias.is_empty() {
        return Err("alias cannot be empty".into());
    }
    if alias.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        return Err("alias cannot start with a digit".into());
    }
    let bad: Vec<char> = alias
        .chars()
        .filter(|c| !(c.is_ascii_alphanumeric() || *c == '_' || *c == '-'))
        .collect();
    if !bad.is_empty() {
        return Err(format!("alias cannot contain {bad:?} — it is typed at a shell prompt"));
    }
    Ok(())
}

/// Rejects a profile set that would generate two functions of the same name.
///
/// The shell keeps only the last definition, so a duplicate alias means one
/// profile silently never runs — with the user's key sitting in a config file
/// that looks installed. Exactly the silent-success shape this tool exists to
/// eliminate, so it is refused rather than resolved.
pub fn check_unique_aliases(profiles: &[Profile]) -> Result<(), String> {
    let mut seen: Vec<&str> = Vec::new();
    for p in profiles {
        if seen.contains(&p.alias.as_str()) {
            return Err(format!(
                "two profiles both use the alias '{}' — the shell would keep only one",
                p.alias
            ));
        }
        seen.push(&p.alias);
    }
    Ok(())
}

/// Commands worth warning about before an alias shadows them.
const COMMON_COMMANDS: &[&str] = &[
    "cd", "ls", "rm", "cp", "mv", "git", "sh", "bash", "zsh", "cat", "echo", "kill", "test",
];

pub fn shadows_common_command(alias: &str) -> bool {
    COMMON_COMMANDS.contains(&alias)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{DangerLevel, ModelMap, Origin};

    fn tmpdir(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("agentport_shell_{tag}_{}", std::process::id()));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).unwrap();
        d
    }

    fn profile(alias: &str, cli: CliKind) -> Profile {
        Profile {
            alias: alias.into(),
            cli,
            provider: "htmustc.id.vn".into(),
            base_url: "https://htmustc.id.vn/v1".into(),
            api_key: "mk-live-secret".into(),
            env_var: "AGENTPORT_HT_API_KEY".into(),
            danger: DangerLevel::Bypass,
            model_map: ModelMap::default(),
            wire_api: None,
            origin: Origin::Manual,
        }
    }

    // ---- the rc file: the seven-Antigravity-lines guard -------------------

    /// The core defect this module exists to prevent.
    #[test]
    fn running_repeatedly_adds_the_rc_line_exactly_once() {
        let home = tmpdir("rc_once");
        let rc = home.join(".zshrc");
        fs::write(&rc, "export PATH=/usr/bin\n").unwrap();

        assert_eq!(
            ensure_rc_line(&rc, &home, ShellKind::Posix).unwrap(),
            RcOutcome::Added
        );
        for _ in 0..6 {
            assert_eq!(
                ensure_rc_line(&rc, &home, ShellKind::Posix).unwrap(),
                RcOutcome::AlreadyPresent
            );
        }

        assert_eq!(active_marker_lines(&fs::read_to_string(&rc).unwrap()), 1);
    }

    /// Counts ACTIVE lines mentioning the script — not raw substring hits.
    /// The rc line names the path twice (`[ -f X ] && . X`), so a substring
    /// count would report two for a single correct line.
    fn active_marker_lines(text: &str) -> usize {
        text.lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .filter(|l| l.contains(RC_MARKER))
            .count()
    }

    #[test]
    fn existing_rc_content_survives() {
        let home = tmpdir("rc_keep");
        let rc = home.join(".zshrc");
        let original = "export PATH=/usr/bin\nalias ll='ls -la'\n";
        fs::write(&rc, original).unwrap();

        ensure_rc_line(&rc, &home, ShellKind::Posix).unwrap();

        let text = fs::read_to_string(&rc).unwrap();
        assert!(text.starts_with(original));
    }

    /// A hand-edited path must still count as registered — a false negative
    /// here appends the duplicate this module is built to avoid.
    #[test]
    fn detects_a_hand_edited_source_line() {
        let rc = "# my setup\n. \"$HOME/.agentport/profiles.sh\"  # edited by hand\n";
        assert!(rc_already_registered(rc));
    }

    /// A commented-out line is not active, so it must NOT count as registered.
    #[test]
    fn a_commented_out_line_does_not_count() {
        let rc = "# [ -f ~/.agentport/profiles.sh ] && . ~/.agentport/profiles.sh\n";
        assert!(!rc_already_registered(rc));
    }

    #[test]
    fn handles_an_rc_file_with_no_trailing_newline() {
        let home = tmpdir("rc_nonl");
        let rc = home.join(".zshrc");
        fs::write(&rc, "export PATH=/usr/bin").unwrap();

        ensure_rc_line(&rc, &home, ShellKind::Posix).unwrap();

        let text = fs::read_to_string(&rc).unwrap();
        assert!(text.contains("export PATH=/usr/bin\n"));
        assert_eq!(active_marker_lines(&text), 1);
    }

    #[test]
    fn creates_the_rc_file_when_absent() {
        let home = tmpdir("rc_new");
        let rc = home.join(".zshrc");

        assert_eq!(
            ensure_rc_line(&rc, &home, ShellKind::Posix).unwrap(),
            RcOutcome::Added
        );
        assert!(rc.exists());
    }

    // ---- the generated script -------------------------------------------

    #[test]
    fn generated_script_is_marked_do_not_edit() {
        let home = tmpdir("hdr");
        let script = render_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::Posix);
        assert!(script.contains("DO NOT EDIT"));
    }

    /// A function, not an alias — every CLI flag must pass through.
    #[test]
    fn posix_uses_functions_so_flags_pass_through() {
        let home = tmpdir("posix_fn");
        let script = render_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::Posix);

        assert!(script.contains("cht() {"));
        assert!(script.contains("\"$@\""));
        assert!(script.contains("command claude --settings"));
    }

    /// PowerShell aliases cannot take arguments at all.
    #[test]
    fn powershell_uses_functions_not_aliases() {
        let home = tmpdir("ps_fn");
        let script =
            render_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::PowerShell);

        assert!(script.contains("function cht {"));
        assert!(script.contains("@args"));
        assert!(!script.contains("Set-Alias"));
    }

    /// The key must be scoped to the command, never exported — an exported key
    /// is readable by every child process, which is the state a real `.zshrc`
    /// was found in.
    #[test]
    fn key_is_scoped_to_the_command_not_exported() {
        let home = tmpdir("noexport");
        let script = render_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::Posix);

        assert!(script.contains("AGENTPORT_HT_API_KEY='mk-live-secret' command claude"));
        assert!(!script.contains("export AGENTPORT_HT_API_KEY"));
    }

    /// Each profile carries its own variable — evidence #3.
    #[test]
    fn each_profile_uses_its_own_env_var() {
        let home = tmpdir("twovars");
        let mut a = profile("cht", CliKind::Claude);
        a.env_var = "VAR_A".into();
        let mut b = profile("co-ht", CliKind::Codex);
        b.env_var = "VAR_B".into();

        let script = render_script(&home, &[a, b], ShellKind::Posix);
        assert!(script.contains("VAR_A="));
        assert!(script.contains("VAR_B="));
    }

    /// A quote inside a key must not break out of the string and execute.
    #[test]
    fn a_quote_in_a_key_cannot_escape_the_string() {
        let home = tmpdir("inject");
        let mut p = profile("cht", CliKind::Claude);
        p.api_key = "abc'; rm -rf /tmp/x; '".into();

        let script = render_script(&home, &[p], ShellKind::Posix);
        assert!(script.contains(r"'\''"));
        assert!(!script.contains("; rm -rf /tmp/x; command"));
    }

    #[test]
    fn powershell_escapes_quotes_by_doubling() {
        let home = tmpdir("ps_quote");
        let mut p = profile("cht", CliKind::Claude);
        p.api_key = "ab'c".into();

        let script = render_script(&home, &[p], ShellKind::PowerShell);
        assert!(script.contains("'ab''c'"));
    }

    #[test]
    fn writes_the_script_and_creates_its_directory() {
        let home = tmpdir("write");
        let path = write_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::Posix).unwrap();

        assert!(path.exists());
        assert!(path.ends_with(".agentport/profiles.sh"));
    }

    /// The app owns this file, so a rewrite replaces rather than appends.
    #[test]
    fn rewriting_replaces_instead_of_appending() {
        let home = tmpdir("replace");
        write_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::Posix).unwrap();
        let path =
            write_script(&home, &[profile("cht", CliKind::Claude)], ShellKind::Posix).unwrap();

        let text = fs::read_to_string(&path).unwrap();
        assert_eq!(text.matches("cht() {").count(), 1);
    }

    // ---- alias validation ------------------------------------------------

    #[test]
    fn rejects_aliases_that_cannot_be_typed() {
        assert!(validate_alias("cht (1)").is_err());
        assert!(validate_alias("cht 1").is_err());
        assert!(validate_alias("c;ht").is_err());
        assert!(validate_alias("").is_err());
        assert!(validate_alias("1cht").is_err());
    }

    #[test]
    fn accepts_the_alias_shapes_already_in_use() {
        for a in ["c", "cht", "cht-cse", "co-ht", "co_ht"] {
            assert!(validate_alias(a).is_ok(), "{a} should be valid");
        }
    }

    /// A duplicate alias means one profile silently never runs.
    #[test]
    fn refuses_two_profiles_sharing_an_alias() {
        let a = profile("cht", CliKind::Claude);
        let b = profile("cht", CliKind::Codex);
        let err = check_unique_aliases(&[a, b]).unwrap_err();
        assert!(err.contains("cht"));
    }

    #[test]
    fn accepts_distinct_aliases() {
        let a = profile("cht", CliKind::Claude);
        let b = profile("co-ht", CliKind::Codex);
        assert!(check_unique_aliases(&[a, b]).is_ok());
    }

    #[test]
    fn flags_aliases_that_shadow_common_commands() {
        assert!(shadows_common_command("cd"));
        assert!(shadows_common_command("git"));
        assert!(!shadows_common_command("cht"));
    }
}
